---
- hosts: servers
  tasks:
  - name: Install Java
    apt: pkg=openjdk-8-jdk state=installed update_cache=true
  - name: Stop app service
    service: name=myapp state=stopped enabled=no
    ignore_errors: yes
  - name: Copy app package
    copy: src=build/libs/java-app-experiment-1.0-SNAPSHOT.war dest=/var/myapp/ mode=u+x
  - name: Register app service
    copy: src=myapp.service dest=/etc/systemd/system
  - name: Start app service
    service: name=myapp state=started enabled=yes
