version: "2.1"

services:
  cassandra1:
    image: cassandra:3.10
    healthcheck:
      test: "if cqlsh < /dev/null; then exit 0; else exit 1; fi"
      interval: 5s
      timeout: 5s
      retries: 100
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    environment:
      CASSANDRA_LISTEN_ADDRESS: 172.26.0.11
      CASSANDRA_CLUSTER_NAME: mycluster
    volumes:
      - ./cassandra1data:/var/lib/cassandra
    networks:
      cassandratest:
        ipv4_address: 172.26.0.11

networks:
  cassandratest:
    external: true
