version: "3.9"

services:
  otel-lgtm:
    image: grafana/otel-lgtm:latest
    container_name: otel-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    stdin_open: true
    tty: true
    restart: unless-stopped
