calc:
  build: ./calculator-service
  environment:
    CALC_ADD_SERVICE_URL: http://adder:8080
    CALC_SUB_SERVICE_URL: http://subtractor:8080
  links:
    - adder
    - subtractor
  ports:
    - "8080:8080"

adder:
  build: ./add-service
  ports:
    - 8080

subtractor:
  build: ./sub-service
  ports:
    - 8080

tester:
  build: .
  links:
    - adder
    - subtractor
    - calc
