version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - apt-get update && apt-get install -y uuid-runtime mysql-client

  build:
    commands:
      - cd rds-mysql-data-import-experiment
      - envTag=${ENV_TAG} app=jdbc-batch-insert-app ./tool.sh run
      - envTag=${ENV_TAG} app=stored-procedure-app ./tool.sh run
