version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - apt-get update && apt-get install -y uuid-runtime mysql-client

  build:
    commands:
      - cd rds-mysql-data-import-experiment
      - export APP_TESTRUNID=$(uuidgen | tail -c 8)
      - N=20
      - APP_SCHOOLS=${N} APP_CLASSES=${N} APP_STUDENTS=${N} envTag=${ENV_TAG} app=jdbc-batch-insert-app ./tool.sh run
      - APP_SCHOOLS=${N} APP_CLASSES=${N} APP_STUDENTS=${N} envTag=${ENV_TAG} app=stored-procedure-app ./tool.sh run
      - APP_SCHOOLS=${N} APP_CLASSES=${N} APP_STUDENTS=${N} envTag=${ENV_TAG} app=load-data-infile-app ./tool.sh run
      - N=40
      - APP_SCHOOLS=${N} APP_CLASSES=${N} APP_STUDENTS=${N} envTag=${ENV_TAG} app=jdbc-batch-insert-app ./tool.sh run
      - APP_SCHOOLS=${N} APP_CLASSES=${N} APP_STUDENTS=${N} envTag=${ENV_TAG} app=stored-procedure-app ./tool.sh run
      - APP_SCHOOLS=${N} APP_CLASSES=${N} APP_STUDENTS=${N} envTag=${ENV_TAG} app=load-data-infile-app ./tool.sh run
      - N=100
      #- APP_SCHOOLS=${N} APP_CLASSES=${N} APP_STUDENTS=${N} envTag=${ENV_TAG} app=jdbc-batch-insert-app ./tool.sh run
      - APP_SCHOOLS=${N} APP_CLASSES=${N} APP_STUDENTS=${N} envTag=${ENV_TAG} app=stored-procedure-app ./tool.sh run
      - APP_SCHOOLS=${N} APP_CLASSES=${N} APP_STUDENTS=${N} envTag=${ENV_TAG} app=load-data-infile-app ./tool.sh run
      - N=200
      #- APP_SCHOOLS=${N} APP_CLASSES=${N} APP_STUDENTS=${N} envTag=${ENV_TAG} app=jdbc-batch-insert-app ./tool.sh run
      - APP_SCHOOLS=${N} APP_CLASSES=${N} APP_STUDENTS=${N} envTag=${ENV_TAG} app=stored-procedure-app ./tool.sh run
      - APP_SCHOOLS=${N} APP_CLASSES=${N} APP_STUDENTS=${N} envTag=${ENV_TAG} app=load-data-infile-app ./tool.sh run
      - echo "testRunId is ${APP_TESTRUNID}"
