version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - apt-get update && apt-get install -y uuid-runtime mysql-client

  build:
    commands:
      - cd rds-mysql-data-import-experiment
      - export APP_TESTRUNID=$(uuidgen | tail -c 8)
      - >
        APP_SCHOOLS=20
        APP_CLASSES=20
        APP_STUDENTS=20
        envTag=${ENV_TAG}
        app=jdbc-batch-insert-app
        ./tool.sh run
      - >
        APP_SCHOOLS=20
        APP_CLASSES=20
        APP_STUDENTS=20
        envTag=${ENV_TAG}
        app=stored-procedure-app
        ./tool.sh run
      - >
        APP_SCHOOLS=20
        APP_CLASSES=20
        APP_STUDENTS=20
        envTag=${ENV_TAG}
        app=load-data-infile-app
        ./tool.sh run
      - >
        APP_SCHOOLS=100
        APP_CLASSES=100
        APP_STUDENTS=100
        envTag=${ENV_TAG}
        app=stored-procedure-app
        ./tool.sh run
      - >
        APP_SCHOOLS=100
        APP_CLASSES=100
        APP_STUDENTS=100
        envTag=${ENV_TAG}
        app=load-data-infile-app
        ./tool.sh run
