version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - apt-get update && apt-get install -y uuid-runtime mysql-client

  build:
    commands:
      - cd rds-mysql-data-import-experiment
      - pwd
      - ls
      - envTag=${ENV_TAG} ./tool.sh run
