version: "2"

services:
  web1:
    image: nginx
    volumes:
      - ./web1/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web1/static/:/opt/web/:ro
    ports:
      - "81:80"
    dns: 172.17.0.1
    environment:
      - DNSEXP_NAME=node1
    network_mode: "bridge"

  web2:
    image: nginx
    volumes:
      - ./web2/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web2/static/:/opt/web/:ro
    ports:
      - "82:80"
    dns: 172.17.0.1
    environment:
      - DNSEXP_NAME=node2
    network_mode: "bridge"

  lb:
    image: nginx
    volumes:
      - ./lb/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - web1
      - web2
    ports:
      - "80:80"
    dns: 172.17.0.1
    environment:
      - DNSEXP_NAME=nodelb
    network_mode: "bridge"

  dnsexp:
    build: ./docker-dns-experiment
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 172.17.0.1:53:1153/udp
    network_mode: "bridge"

  tester:
    image: ubuntu
    command: bash -c "ping node1 -c3 && ping node2 -c3 && ping nodelb -c3"
    links:
      - web1
      - web2
      - lb
      - dnsexp
    dns: 172.17.0.1
    network_mode: "bridge"
