version: "2"

services:
  web1:
    image: nginx
    volumes:
      - ./web1/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web1/static/:/opt/web/:ro
    ports:
      - "81:80"
    networks:
      test:
        ipv4_address: 172.25.0.11

  web2:
    image: nginx
    volumes:
      - ./web2/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web2/static/:/opt/web/:ro
    ports:
      - "82:80"
    networks:
      test:
        ipv4_address: 172.25.0.22

  lb:
    image: nginx
    volumes:
      - ./lb/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - web1
      - web2
    ports:
      - "80:80"
    networks:
      test:
        ipv4_address: 172.25.0.33

  tester:
    image: ubuntu
    command: bash -c "ifconfig && ping 172.25.0.11 -c3 && ping 172.25.0.22 -c3 && ping 172.25.0.33 -c3"
    links:
      - web1
      - web2
      - lb
    networks:
      test:
        ipv4_address: 172.25.0.99

networks:
  test:
    external: true
